name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies (including PyInstaller)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Step 4: Build the EXE file
      - name: Build EXE
        run: pyinstaller --onefile usb_reader.py

      # Step 5: Debug PyInstaller Output (Optional, for troubleshooting)
      - name: Debug PyInstaller Output
        run: |
          echo "Checking dist directory contents:"
          dir dist

      # Step 6: Upload the EXE file as an artifact
      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v2
        with:
          name: usb_reader
          path: dist/usb_reader.exe